services:
  php:
    build:
      context: .
    container_name: php_latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - mysql

  mysql:
    build:
      context: ./docker/mysql
    container_name: mysql_latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - mysql_network
    restart: always

networks:
  mysql_network:
    driver: bridge
